spring:
  application:
    name: demo-app
  elasticsearch:
    uris: https://localhost:9200
    username: elastic
    password: gu3w106jMJ6riv1*BCnz

  data:
    mongodb:
      host: localhost
      port: 27017
      database: Quara_db
      auto-index-creation: true

server:
  port: 6636