spring:
  application:
    name: demo-app

  elasticsearch:
    uris: http://localhost:9200


  data:
    mongodb:
      host: localhost
      port: 27017
      database: Quara_db
      auto-index-creation: true

server:
  port: 6636



